// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tutorial.Kudvenkad.Api.Contexts;

namespace Tutorial.Kudvenkad.Api.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20200601231709_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tutorials.Kudvenkat.Models.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "IT"
                        },
                        new
                        {
                            ID = 2,
                            Name = "HR"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Payroll"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("Tutorials.Kudvenkat.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Birthday = new DateTime(1994, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "eslam.alhiki94@gmail.com",
                            FirstName = "Islam",
                            Gender = 0,
                            LastName = "Alshiki",
                            Photo = "image.jpg"
                        },
                        new
                        {
                            ID = 2,
                            Birthday = new DateTime(1994, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "Abdulrahman.Alfaydi@gmail.com",
                            FirstName = "Abdulrahman",
                            Gender = 0,
                            LastName = "Alfaydi",
                            Photo = "image.jpg"
                        },
                        new
                        {
                            ID = 3,
                            Birthday = new DateTime(1991, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "Ali.Alawami@gmail.com",
                            FirstName = "Ali",
                            Gender = 0,
                            LastName = "Alawami",
                            Photo = "image.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
